import OpenAI from 'openai';
import { configDotenv } from 'dotenv';
configDotenv();

const oi = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

export const processCustomerOrder = async (text: string) => {
  //   name, item, quantity and address
  // quantify should be greater than 0
  // JSON object
  const prompt = `
    You will be prompted with customer's order enclosed within triple backticks.
    Step1: Identify following keys:
    - name: Name of the customer
    - item: Name of the item purchased
    - quantity: Number of items purchased.
    - address: delivery address
    Step 2: 
    If all the above keys are present and quantity is greater than 0:
        return JSON object with above keys. Make sure value of the quantity is in number.
    if any of the key is missing, return JSON object marking the value that key as missing.
    
  `;

  try {
    const response = await oi.chat.completions.create({
      model: 'gpt-4o-mini',
      messages: [
        { role: 'system', content: prompt },
        { role: 'user', content: `\`\`\`${text}\`\`\`` },
      ],
    });

    const data = response.choices[0].message.content;
    if (!data) {
      console.log({ error: 'No text generated by openai' });
      return;
    }
    const processedText = JSON.parse(data);
    console.log(processedText);
  } catch (error) {
    console.log({ error: `Failed to generate text by openai, ${error}` });
    return { error: `Failed to generate text by openai, ${error}` };
  }
};

// customer order
const customerOrder =
  'Hi, there! I purchased ten shampoos. My name is. Can you please deliver it to my address?';
const text = '';

processCustomerOrder(customerOrder);
